/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "sacd_ripper.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif


/* The following messages exceed 64kB in size: ServerResponse */

/* The PB_FIELD_32BIT compilation option must be defined to support messages that exceed 64 kB in size. */
#ifndef PB_FIELD_32BIT
#error Enable PB_FIELD_32BIT to support messages exceeding 64kB in size: ServerResponse
#endif
PB_BIND(ServerRequest, ServerRequest, AUTO)


PB_BIND(ServerResponse, ServerResponse, 4)







