/* Automatically generated by version.sh, do not manually edit! */
#ifndef SAUTIL_FFVERSION_H
#define SAUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2025-12-09-e3a79c89d9"
#endif /* SAUTIL_FFVERSION_H */
